version: 2

jobs:
  deploy:
    docker:
      - image: circleci/node:12.14.1
    steps:
      - checkout
      - run:
          name: npm install
          command: npm i
      - run:
          name: nuxt generate
          command: npm run generate
      - run:
          name: deploy to Firebase Hosting
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN

workflows:
  version: 2
  deploy_master:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
