version: 2

jobs:
  deploy:
    docker:
      - image: circleci/node:12.14.1
    steps:
      - checkout
      - run:
          name: copy env file
          command: cp .env.dist .env
      - run:
          name: install npm module
          command: npm i
      - run:
          name: generate nuxt
          command: npm run generate
      - run:
          name: deploy to firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN

workflows:
  version: 2
  deploy_master:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
