# https://circleci.com/blog/automatically-deploy-a-gatsby-site-to-firebase-hosting/

version: 2

jobs:
  deploy:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          command: yarn generate
      - run:
          command: yarn add -D firebase-tools
      - run:
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN

workflows:
  version: 2
  production:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
