name: main.yml

on:
  push:
    branches:
      - master

jobs:
  build:
    name: jobs-build
    runs-on: ubuntu-latest
    steps:
      - name: uses actions/checkout 
        uses: actions/checkout@v1
        with:
          submodules: true
      - name: uses peaceiris/actions-hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
      - name: build hugo project
        run: |
          hugo
      - name: uses actions/upload-artifact
        uses: actions/upload-artifact@master
        with:
          name: public
          path: public

  deploy:
    name: jobs-deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: uses actions/checkout
        uses: actions/checkout@master
      - name: uses actions/download-artifact
        uses: actions/download-artifact@master
        with:
          name: public
      - name: uses w9jds/firebase-action
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: yurikago-blog
