# https://dev.classmethod.jp/articles/github-actions-hugo-firebase/
name: main.yml

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: jobs-deploy
    runs-on: ubuntu-latest
    steps:
      - name: uses actions/checkout
        uses: actions/checkout@master@v1
      - name: uses peaceiris/actions-hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
      - name: build hugo project
        run: |
          hugo
      - name: uses w9jds/firebase-action
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: yurikago-blog
